app_commands = {
    "calculator": "calc",
    "notepad": "notepad",
    "paint": "mspaint",
    "wordpad": "write",
    "task manager": "taskmgr",
    "command prompt": "cmd",
    "powershell": "powershell",
    "control panel": "control",
    "file explorer": "explorer",
    "registry editor": "regedit",
    "event viewer": "eventvwr",
    "disk management": "diskmgmt.msc",
    "device manager": "devmgmt.msc",
    "services": "services.msc",
    "performance monitor": "perfmon",
    "system configuration": "msconfig",
    "remote desktop": "mstsc",
    "windows update": "wuapp",
    "internet explorer": "iexplore",
    "system information": "msinfo32",
    "resource monitor": "resmon",
    "windows defender": "ms-settings:windowsdefender",  # Modern Windows Settings link
    "bluetooth settings": "ms-settings:bluetooth",
    "network settings": "ms-settings:network",
    "volume mixer": "sndvol",
    "sound settings": "mmsys.cpl",
    "add or remove programs": "appwiz.cpl"
}
